# Generated by Django 4.0.2 on 2022-02-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='cartId',
            new_name='cart',
        ),
    ]
